# Generated by Django 3.2.5 on 2021-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(blank=True, max_length=200)),
                ('stripe_price_id', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default='')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
