# Generated by Django 3.2.5 on 2021-09-15 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='stripe_price_id',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='post_id',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='thumbnail',
            field=models.FileField(max_length=200, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.SlugField(default='')),
                ('images', models.FileField(max_length=200, upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
    ]
