# Generated by Django 3.2.5 on 2021-08-11 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cables', models.CharField(max_length=100)),
                ('deskmats', models.CharField(max_length=100)),
                ('keyboards', models.CharField(max_length=100)),
                ('keycaps', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
                ('switches', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
