# Generated by Django 3.2.5 on 2021-07-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_id_stripe',
            new_name='stripe_id',
        ),
    ]
