# Generated by Django 3.2.5 on 2021-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='country',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stripe_price_id',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stripe_product_id',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
