# Generated by Django 3.2.5 on 2021-09-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210903_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
