# Generated by Django 3.2.5 on 2021-09-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210912_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='images',
            field=models.FileField(max_length=200, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(max_length=200, upload_to='images/'),
        ),
    ]
