# Generated by Django 3.2.5 on 2021-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210915_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='post_id',
            field=models.SlugField(default='', unique=True),
        ),
    ]
