# Generated by Django 3.2.5 on 2021-09-07 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210907_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
        ),
    ]
