# Generated by Django 3.2.5 on 2021-09-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210908_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='images',
        ),
    ]
