# Generated by Django 3.2.5 on 2021-07-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210728_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
