# Generated by Django 3.2.5 on 2021-09-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210907_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='product_id',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='stripe_product_id',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
