# Generated by Django 3.2.5 on 2021-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='country',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
