# Generated by Django 3.2.5 on 2021-09-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210912_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
