# Generated by Django 3.2.5 on 2021-09-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
