# Generated by Django 3.2.5 on 2021-08-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210811_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
