# Generated by Django 3.2.5 on 2021-09-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='thumbnail',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
