# Generated by Django 3.2.5 on 2021-07-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210729_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
