# Generated by Django 3.2.5 on 2021-09-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Products'},
        ),
    ]
