# Generated by Django 3.2.5 on 2021-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
