# Generated by Django 3.2.7 on 2021-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='reviewer',
            field=models.CharField(default='', max_length=20),
        ),
    ]
