# Generated by Django 3.2.5 on 2021-08-11 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
