# Generated by Django 3.2.5 on 2021-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='images',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
