# Generated by Django 3.2.7 on 2021-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210916_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(default='', max_length=20),
        ),
    ]
