# Generated by Django 3.2.5 on 2021-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
