# Generated by Django 3.2.5 on 2021-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_imagemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='images',
            field=models.FileField(max_length=200, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='thumbnail',
            field=models.FileField(max_length=200, upload_to='thumbnails/'),
        ),
    ]
