# Generated by Django 3.2.7 on 2021-09-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_savedmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedmodel',
            old_name='post',
            new_name='post_id',
        ),
    ]
