# Generated by Django 3.2.5 on 2021-08-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210813_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
