# Generated by Django 3.2.7 on 2021-09-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_post_savedmodel_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedModel',
        ),
    ]
