# Generated by Django 3.2.5 on 2021-08-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmodel_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Product images',
            },
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productimagesmodel'),
            preserve_default=False,
        ),
    ]
