# Generated by Django 3.2.5 on 2021-08-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210816_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImagesModel',
            new_name='ImageModel',
        ),
    ]
