# Generated by Django 3.2.5 on 2021-08-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_productimagesmodel_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
