# Generated by Django 3.2.5 on 2021-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210817_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stripe_price_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stripe_product_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
