# Generated by Django 3.2.5 on 2021-08-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210817_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='date_added',
            new_name='date',
        ),
    ]
